service: logging-metrics-demo

plugins:
 - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
      Resource: "*"

functions:
  custom-metrics:
    handler: functions/custom-metrics/handler.handler
    description: Sends custom CloudWatch metrics asynchronously

  usage-metrics:
    handler: functions/usage-metrics/handler.handler
    description: Tracks Memory Usage and Billed Duration as metrics

  test-api:
    handler: functions/test-api/handler.handler
    events: 
      - http:
          path: /
          method: get